# Copyright (c) Meta Platforms, Inc. and its affiliates.

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Visuo-tactile config

defaults:
  - data: default
  - eval: default 
  - train: default
  - pose: default
  - scene: default
  - viz: default
  - sensor@sensor0: realsense
  - sensor@sensor1: digit
  - sensor@sensor2: digit
  - sensor@sensor3: digit
  - sensor@sensor4: digit
  - _self_

mode: vitac
occlusion: False

sensor0: 
  name: realsense_front_left
sensor1: 
  name: digit_thumb
sensor2: 
  name: digit_index
sensor3: 
  name: digit_middle
sensor4: 
  name: digit_ring
