# Copyright (c) Meta Platforms, Inc. and its affiliates.

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# Config for the realsense

name: 

sampling: 
  n_rays: 400
  n_strat_samples: 30
  n_surf_samples: 10
  depth_range: [0.3, 1.0]   # [0.6, 6.0] for D455, [0.3, 3.0] for D435
  surface_samples_offset: 1e-3 # needs to be small to capture surface detail
  dist_behind_surf: 2e-2 # needs to be larger to carve out object extents
  loss_ratio : 1.0
  free_space_ratio: 0.7  # used for mapping, but not tracking

kf_min_loss: 1e-2

masks: sam_vit_l # read (gt from file), sam_vit_h, sam_vit_l, sam_vit_b  
sim_noise_iters: 5

# (empirical) prefers this area of mask from multi-mask SAM output
optimal_mask_size: 
  realsense_front_left: 15000.0
  realsense_back_right: 5000.0
  realsense_top_down: 4000.0

# (empirical) z-offset for pixel prompt wrt grasp center
sam_offset:
  realsense_front_left: 0.0
  realsense_back_right: 0.01
  realsense_top_down: 0.0


viz:
  reduce_factor: 1
  reduce_factor_up: 1